# Generated by Django 4.2.18 on 2026-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='image',
        ),
        migrations.AddField(
            model_name='design',
            name='gallery_image',
            field=models.ImageField(default='default.png', upload_to='designs/gallery/', verbose_name='Снимка за галерията'),
        ),
        migrations.AddField(
            model_name='design',
            name='nail_image',
            field=models.ImageField(default='default.png', upload_to='designs/nails/', verbose_name='PNG за обработка (1 нокът)'),
        ),
    ]
