# Generated by Django 4.2.18 on 2026-04-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manicuredesign',
            options={'verbose_name': 'Дизайн за маникюр', 'verbose_name_plural': 'Дизайни за маникюр'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'Потребителска сесия', 'verbose_name_plural': 'Потребителски сесии'},
        ),
        migrations.AddField(
            model_name='usersession',
            name='selected_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sessions', to='main.manicuredesign', verbose_name='Избран дизайн'),
        ),
        migrations.AlterField(
            model_name='manicuredesign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Създадено на'),
        ),
        migrations.AlterField(
            model_name='manicuredesign',
            name='image',
            field=models.ImageField(upload_to='designs/', verbose_name='Изображение на дизайна'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Качено на'),
        ),
    ]
