# Generated by Django 4.2.18 on 2026-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_manicuredesign_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manicuredesign',
            name='image',
        ),
        migrations.AddField(
            model_name='manicuredesign',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/gallery/', verbose_name='Изображение за галерията'),
        ),
        migrations.AddField(
            model_name='manicuredesign',
            name='simulation_image',
            field=models.ImageField(null=True, upload_to='designs/simulation/', verbose_name='Изображение за симулация'),
        ),
    ]
