# Generated by Django 4.2.18 on 2026-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_manicuredesign_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manicuredesign',
            name='gallery_image',
            field=models.ImageField(upload_to='designs/gallery/', verbose_name='Изображение за галерията'),
        ),
        migrations.AlterField(
            model_name='manicuredesign',
            name='simulation_image',
            field=models.ImageField(upload_to='designs/simulation/', verbose_name='Изображение за симулация'),
        ),
    ]
